const Amenities = [
  {
    location: "school",
    times: "24 hours",
    distance: "1 mile",
    address: "123 this place now",
    type: ["Shelter", "Learn"],
    availability: "20",
    key: "1",
  },
  {
    location: "fitness",
    times: "10:00 am - 6: 00 pm",
    distance: "800 feet",
    address: "123 your place",
    type: ["Health", "Hygiene"],
    availability: "2",
    key: "2",
  },
  {
    location: "plaza",
    times: "12:00 pm - 9:00 pm",
    distance: "3 miles",
    address: "123 my house",
    type: ["Shop", "Family"],
    availability: "0",
    key: "3",
  },
  {
    location: "haircuts",
    times: "7:00 am - 4:00 am",
    distance: "0.4 mile",
    address: `'123 I don't know'`,
    type: ["Work", "Hygiene"],
    availability: "7",
    key: "4",
  },
  {
    location: "restaurant",
    times: "7:00 am - 4:00 am",
    distance: "0.4 mile",
    address: `'123 I don't know'`,
    type: ["Food", "Finance"],
    availability: "12",
    key: "5",
  },
  {
    location: "sleeping",
    times: "7:00 am - 4:00 am",
    distance: "0.4 mile",
    address: `'123 I don't know'`,
    type: ["Shelter", "Health", "Family"],
    availability: "15",
    key: "6",
  },
];

export default Amenities;
